### ISSUE TITLE
401 Unauthorized on CSS328-24P-4S+

### ISSUE THREAD

**Issue by adams-family** [patagonaa/prometheus-mikrotik-swos-exporter#1]
Hi,

I was trying your library on a `CSS328-24P-4S+` but unfortunately I get 401 Unauthorized all the time. IP, username and passwords are copy & paste to avoid any possible mistakes.

SwOS version is: 2.12

Any idea what can be wrong?

```
{
  data: '<h1>401 Unauthorized</h1>',
  status: 401,
  headers: {
    'www-authenticate': 'Digest realm="CSS328-24P-4S+", qop="auth", nonce="97eaf5dd", stale=FALSE',
    'content-type': 'text/html'
  },
  res: {
    status: 401,
    statusCode: 401,
    statusMessage: 'Unauthorized',
    headers: {
      'www-authenticate': 'Digest realm="CSS328-24P-4S+", qop="auth", nonce="97eaf5dd", stale=FALSE',
      'content-type': 'text/html'
    },
    size: 25,
    aborted: false,
    rt: 2,
    keepAliveSocket: false,
    data: '<h1>401 Unauthorized</h1>',
    requestUrls: [ 'http://192.168.88.1/link.b', 'http://192.168.88.1/link.b' ],
    timing: null,
    remoteAddress: '192.168.88.1',
    remotePort: 80,
    socketHandledRequests: 1,
    socketHandledResponses: 1
  }
}
```

**Comment by patagonaa** [comment]
Honestly, I have no idea and I don't even know how the digest authentication really works.
Did you upgrade the urllib version? Because the current version breaks compatibility by making all headers lowercase (the MikroTik switches don't like this even if the HTTP spec allows this).

Also, unless you actually need SFP RX/TX power statistics, you should use SNMP instead of this (I removed everything the switches output via SNMP anyway). There are some hints how to do this in the readme file.
